// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package GRPC_Protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CourseMethodsClient is the client API for CourseMethods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseMethodsClient interface {
	PostCourse(ctx context.Context, in *PostCourseRequest, opts ...grpc.CallOption) (*PostCourseReply, error)
	GetCourseByID(ctx context.Context, in *GetCourseByIDRequest, opts ...grpc.CallOption) (*GetCourseByIDReply, error)
	GetCourses(ctx context.Context, in *GetCourseListRequest, opts ...grpc.CallOption) (*GetCourseListReply, error)
	DeleteCourseByID(ctx context.Context, in *DeleteCourseByIDRequest, opts ...grpc.CallOption) (*DeleteCourseByIDReply, error)
}

type courseMethodsClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseMethodsClient(cc grpc.ClientConnInterface) CourseMethodsClient {
	return &courseMethodsClient{cc}
}

func (c *courseMethodsClient) PostCourse(ctx context.Context, in *PostCourseRequest, opts ...grpc.CallOption) (*PostCourseReply, error) {
	out := new(PostCourseReply)
	err := c.cc.Invoke(ctx, "/main.CourseMethods/postCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseMethodsClient) GetCourseByID(ctx context.Context, in *GetCourseByIDRequest, opts ...grpc.CallOption) (*GetCourseByIDReply, error) {
	out := new(GetCourseByIDReply)
	err := c.cc.Invoke(ctx, "/main.CourseMethods/getCourseByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseMethodsClient) GetCourses(ctx context.Context, in *GetCourseListRequest, opts ...grpc.CallOption) (*GetCourseListReply, error) {
	out := new(GetCourseListReply)
	err := c.cc.Invoke(ctx, "/main.CourseMethods/getCourses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseMethodsClient) DeleteCourseByID(ctx context.Context, in *DeleteCourseByIDRequest, opts ...grpc.CallOption) (*DeleteCourseByIDReply, error) {
	out := new(DeleteCourseByIDReply)
	err := c.cc.Invoke(ctx, "/main.CourseMethods/deleteCourseByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseMethodsServer is the server API for CourseMethods service.
// All implementations must embed UnimplementedCourseMethodsServer
// for forward compatibility
type CourseMethodsServer interface {
	PostCourse(context.Context, *PostCourseRequest) (*PostCourseReply, error)
	GetCourseByID(context.Context, *GetCourseByIDRequest) (*GetCourseByIDReply, error)
	GetCourses(context.Context, *GetCourseListRequest) (*GetCourseListReply, error)
	DeleteCourseByID(context.Context, *DeleteCourseByIDRequest) (*DeleteCourseByIDReply, error)
	mustEmbedUnimplementedCourseMethodsServer()
}

// UnimplementedCourseMethodsServer must be embedded to have forward compatible implementations.
type UnimplementedCourseMethodsServer struct {
}

func (UnimplementedCourseMethodsServer) PostCourse(context.Context, *PostCourseRequest) (*PostCourseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCourse not implemented")
}
func (UnimplementedCourseMethodsServer) GetCourseByID(context.Context, *GetCourseByIDRequest) (*GetCourseByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseByID not implemented")
}
func (UnimplementedCourseMethodsServer) GetCourses(context.Context, *GetCourseListRequest) (*GetCourseListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourses not implemented")
}
func (UnimplementedCourseMethodsServer) DeleteCourseByID(context.Context, *DeleteCourseByIDRequest) (*DeleteCourseByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourseByID not implemented")
}
func (UnimplementedCourseMethodsServer) mustEmbedUnimplementedCourseMethodsServer() {}

// UnsafeCourseMethodsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseMethodsServer will
// result in compilation errors.
type UnsafeCourseMethodsServer interface {
	mustEmbedUnimplementedCourseMethodsServer()
}

func RegisterCourseMethodsServer(s grpc.ServiceRegistrar, srv CourseMethodsServer) {
	s.RegisterService(&CourseMethods_ServiceDesc, srv)
}

func _CourseMethods_PostCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseMethodsServer).PostCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CourseMethods/postCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseMethodsServer).PostCourse(ctx, req.(*PostCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseMethods_GetCourseByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseMethodsServer).GetCourseByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CourseMethods/getCourseByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseMethodsServer).GetCourseByID(ctx, req.(*GetCourseByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseMethods_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseMethodsServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CourseMethods/getCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseMethodsServer).GetCourses(ctx, req.(*GetCourseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseMethods_DeleteCourseByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourseByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseMethodsServer).DeleteCourseByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CourseMethods/deleteCourseByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseMethodsServer).DeleteCourseByID(ctx, req.(*DeleteCourseByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseMethods_ServiceDesc is the grpc.ServiceDesc for CourseMethods service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseMethods_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.CourseMethods",
	HandlerType: (*CourseMethodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "postCourse",
			Handler:    _CourseMethods_PostCourse_Handler,
		},
		{
			MethodName: "getCourseByID",
			Handler:    _CourseMethods_GetCourseByID_Handler,
		},
		{
			MethodName: "getCourses",
			Handler:    _CourseMethods_GetCourses_Handler,
		},
		{
			MethodName: "deleteCourseByID",
			Handler:    _CourseMethods_DeleteCourseByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GRPC_Protocol/Course.proto",
}
